"""User manual slide copy (English) for build_deck.py. Point = (lead, one-line description); <b> = UI element pill, <code> = keys/values."""

DECK = {
    "name": "bpm-manual-user-en",
    "lang": "en",
    "html_title": "BPM User Manual",
    "label": "Business Process Map · User Manual",
    "date": "2026-10-02",
    "cover": {
        "eyebrow": "User Manual · English edition",
        "h1": "Business Process Map<br>User Manual",
        "sub": "Draw processes as flowcharts, manage them as versions, finalize through approval.",
        "meta": ["Company process-map system", "As of 2026-09-30"],
        "hint": "Navigate with <kbd>←</kbd><kbd>→</kbd> or click the screen edges · <kbd>Home</kbd> to restart",
    },
    "toc": {"kicker": "Contents", "sec": "What's inside", "title": "What's inside"},
    "closing": {
        "h1": "Happy mapping",
        "sub": "Questions? Use the in-app <b>Manual</b> and <b>Feedback</b>. Admins, see the Administrator Manual.",
    },
    "chapter_word": "Chapter",
    "chapters": [
        {
            "title": "Getting Started", "short": "Getting Started",
            "desc": "Sign in, learn the screens, and understand your role on a map.",
            "slides": [
                {"title": "Signing in", "shot": True, "caption": "Login screen (development example)", "pts": [
                    ("Keycloak SSO", "<b>Sign in with Keycloak</b> with your company account."),
                    ("Auto sign-in · deep links", "After the first time you're signed in automatically and land on the screen you opened."),
                    ("LDAP servers", "An ID/password form instead. Admin-issued <b>local accounts</b> work too."),
                    ("Development", "<b>Sign in with a test account</b>."),
                ]},
                {"title": "Screens at a glance", "shot": True, "pts": [
                    ("Top tabs", "Maps · Notices · Inbox."),
                    ("Top bar", "Manual (KO/EN, search), Feedback, the bell, <b>Settings</b>, 한/EN toggle."),
                    ("Personal dashboard", "Right side of Home. Profile · five activity tiles · six sections."),
                    ("Quick search", "Press <code>/</code> on the map list or in the manual."),
                ]},
                {"title": "Roles and visibility", "pts": [
                    ("Owner", "Everything. Edit, manage collaborators, approvers and visibility, delete."),
                    ("Editor", "Edit the map and its draft versions."),
                    ("Viewer", "Read-only. Browse, compare, comment."),
                    ("Approver", "Review and approve or reject submitted versions."),
                    ("Owning department", "One per map. Its members hold Editor automatically."),
                    ("Visibility", "<b>Public</b> is viewable by everyone, <b>Private</b> by collaborators and approvers only."),
                    ("Category admins", "Framework-only role. They edit and confirm the linkage canvases of their category and below (⑨)."),
                ]},
            ],
        },
        {
            "title": "Home · Finding &amp; Managing Maps", "short": "Home",
            "desc": "Browse maps by org tree or framework; create, copy, and manage settings.",
            "slides": [
                {"title": "Finding maps &amp; the detail panel", "shot": True, "pts": [
                    ("Org tree", "Browse by department, yours pinned on top. Managed canvases sit in an <b>L5 canvases</b> group."),
                    ("Search and two filter rows", "All/Public/Private and <b>Sort</b> on top. Status · Role · Issues · <b>Type</b> below."),
                    ("Detail panel", "Click a card. Owner, owning department, members, version history."),
                    ("Owner unconfirmed", "Interview-imported maps. Cleared by Transfer ownership."),
                    ("Notes", "Read-only interview source notes and owner-managed <b>Notes</b>. Collaborators edit right on the card."),
                ]},
                {"title": "Personal dashboard &amp; delayed navigation", "shot": True, "caption": "Home personal dashboard", "pts": [
                    ("Six sections", "Recently opened · Framework · My department · My documents · Needs approval · Recent changes. Profile and tiles stay pinned."),
                    ("My department", "Your department's own maps. Sub-departments fold into one line, widened by the <b>scope dropdown</b>."),
                    ("Status | Version tabs", "Distribution on the My department and My documents cards. Click a legend to filter."),
                    ("N more", "A few rows per section. A map in several sections gets a <b>left accent bar</b> on hover."),
                    ("Delayed one-click navigation", "Tiles and rows run after a <b>0.6 s countdown</b>. Click the layer to cancel."),
                ]},
                {"title": "The Framework pill · assign, move, hand off", "shot": True, "pts": [
                    ("Framework pill", "On the card: <b>Add to framework</b> · <b>Unassign</b> · <b>Transfer slot</b>. L5 only."),
                    ("Apply now vs request", "That L5's admin or a sysadmin applies at once. Anyone else files a request the L5 admins decide."),
                    ("Move to another L5", "Both L5s' admins approve. A <b>progress (n/m)</b> banner shows meanwhile; withdrawable."),
                    ("Delete · copy-and-retire", "Same path. <b>Copy inherits the slot</b> or <b>Free the slot</b>."),
                    ("Category summary card", "Click a category row. Children, L5s, maps, admins, subtree confirmation."),
                ]},
                {"title": "People cards &amp; org info", "shot": True, "pts": [
                    ("Person card", "Hover a name 0.7 s or click. KO/EN names, title, org path, Open messenger."),
                    ("Right-click a name", "<b>Send message</b> · <b>Info</b>."),
                    ("Org info modal", "Click a department card. Members, sub-organizations, path upward."),
                    ("Name order", "Follows your language setting. Korean UI puts Korean names first."),
                ]},
                {"title": "Creating a map", "shot": True, "pts": [
                    ("New map", "Name · description · visibility."),
                    ("Owning department required", "Org-tree picker. Its members always hold Editor."),
                    ("At least one approver", "A map cannot be created without one."),
                    ("Initial collaborators", "People, teams or groups as Viewer/Editor. Sorted by org proximity."),
                    ("Draw right away", "Start and End are pre-seeded. <b>Create from CSV</b> builds a pre-filled map."),
                ]},
                {"title": "Copying &amp; replacing the original", "shot": True, "pts": [
                    ("Copy", "Published maps only. Pick the version; the copy opens as a new draft."),
                    ("Replace the original", "Check \"Move the original to the trash\". The copy keeps the name, the original is trashed for 7 days."),
                    ("Rosters carry over", "Collaborators and approvers are pre-loaded to review, then notified."),
                    ("Slot on copy", "A slotted original goes through approval. <b>Inherit</b> or <b>Free</b> the slot."),
                    ("Plain deletion", "7 days in the trash, then purged. Restore under Settings → Scheduled deletion."),
                ]},
                {"title": "Map Settings · Collaborators", "shot": True, "pts": [
                    ("Add Viewer / Editor", "People, teams or user groups. Default list sorted by org proximity."),
                    ("Staged changes", "To add / Change / Remove pills, applied with <b>Save changes</b>, dropped with <b>Discard</b>."),
                    ("Forecast icons", "⚡ instant, ⏳ needs approval (removing or demoting an Editor)."),
                    ("Approval pending", "Tag on pending requests. Hover your own to <b>Withdraw</b>."),
                    ("Undo", "Right after saving, revert that one save."),
                ]},
                {"title": "Map Settings · name, visibility &amp; more", "shot": True, "pts": [
                    ("Name · owning department", "Owner/admin change instantly, editors file a request. Derived Editor access follows the new department."),
                    ("Conditions &amp; GMP card", "Details tab of interview-imported maps. Settle GMP and start/end conditions next to the source text."),
                    ("Visibility change", "Needs approval. Impact preview plus deciding approvers; withdraw while pending."),
                    ("Subprocess designation", "Needs a published version. <b>Attributes / Metric tiles / Detail tiles</b> (⑤)."),
                    ("Danger Zone", "Transfer ownership, delete map (Owner only)."),
                ]},
            ],
        },
        {
            "title": "Editing · The Basics", "short": "Editing Basics",
            "desc": "The editor, canvas navigation, creating and connecting nodes, tidying and saving.",
            "slides": [
                {"title": "The editor at a glance", "shot": True, "pts": [
                    ("Top bar", "Map menu · version selector · undo/redo · library · AI · Save."),
                    ("Side panels", "Outline tree and shortcut card on the left, inspector (Properties / Map / Approval / Activity) on the right."),
                    ("Node display fields", "Map tab <b>Node display</b> or the <b>eye icon</b> card next to the zoom pill."),
                    ("Framework chip", "Top-left on registered maps. Expand to jump to sibling maps."),
                    ("AI consultant balloon", "On a brand-new map. Start opens the interview (⑧)."),
                ]},
                {"title": "Moving around the canvas", "shot": True, "pts": [
                    ("Wheel", "Vertical pan. <code>Shift</code>+wheel horizontal, <code>Ctrl</code>+wheel zoom."),
                    ("Pan and box-select", "Hold <code>Space</code> and drag to pan. Drag empty canvas to box-select."),
                    ("Right-click", "Context menu for node, edge or canvas."),
                    ("Auto shift", "When a node grows, nodes below shift on screen. Saved coordinates stay."),
                ]},
                {"title": "Creating nodes", "shot": True, "pts": [
                    ("Add", "<b>Right-click</b> the canvas or <b>Add node</b> in the inspector."),
                    ("Five types", "Start (one) · Process · Decision · End (one primary) · Subprocess."),
                    ("Rename", "Double-click or <code>F2</code>. <code>Enter</code> commits, <code>Shift+Enter</code> breaks the line."),
                    ("Copy · duplicate", "<code>Ctrl+C/V</code> across maps, <code>Ctrl</code>+drag duplicates. Duplicate names get (2)."),
                ]},
                {"title": "Connecting nodes", "shot": True, "pts": [
                    ("Drag a handle", "Dropping on a node's body connects to the default handle (snap preview)."),
                    ("Splits use a decision or a parallel exit", "One-of-several uses a <b>Decision</b> (Yes/No labels); concurrent work uses a right-click <b>Parallel exit</b> (two or more). Start is parallel by default."),
                    ("Edge labels", "Right-click or <code>F2</code>. Line breaks supported."),
                    ("Line style", "Per edge: curved / stepped / straight. Change all in the Map tab's <b>Edge style</b>."),
                    ("Drop zones", "Drag a node near another to insert before / after / swap / group."),
                ]},
                {"title": "Parallel exits and flow pulse", "shot": "manual8/en-parallel.jpg", "pts": [
                    ("Turn on", "Right-click a node, <b>Parallel exit</b>. Subprocesses pick per end."),
                    ("Rule", "A parallel exit needs two or more connections. No insert prompt."),
                    ("Hover badge", "<b>N in parallel</b> above the node. A faint inner line once on, even before connecting."),
                    ("Flow pulse", "Parallel dots set off together and reach three quarters at once. Decision dots stop, blink in turn, then one branch moves on."),
                    ("Reduced motion", "Hidden when the OS reduce-motion setting is on."),
                ]},
                {"title": "Tidying · layout, groups, bulk edit", "pts": [
                    ("Auto layout", "Horizontal <code>Shift+L</code> · vertical <code>Shift+K</code>. The main path snaps to one line."),
                    ("Axis lock · align · distribute", "<code>Shift</code>+drag locks the axis, <code>Alt+W/C/T/X</code> aligns, <code>Alt+R/V</code> distributes."),
                    ("Group", "Select 2+ nodes, <code>Ctrl+G</code>. Double-click the title to rename, drag it to move."),
                    ("Group bulk edit", "Pick a field under Attributes / Metrics / I/O and set or clear it for every member."),
                ]},
                {"title": "Search &amp; following the flow", "shot": True, "pts": [
                    ("Node search", "<code>/</code>. Korean <b>chosung</b> supported; matches jump and highlight."),
                    ("Outline", "Click an entry to focus that node."),
                    ("Along the flow", "<code>Tab</code>/<code>Shift+Tab</code> next/previous node, expanded children included."),
                    ("Flow highlight", "<code>]</code>/<code>[</code> grow or shrink. Incoming teal, outgoing orange, selected violet."),
                    ("Node comments", "<code>Ctrl+Enter</code> sends. Read-only users can comment too."),
                ]},
                {"title": "Saving &amp; validation", "pts": [
                    ("Autosave", "About 2 s after you stop. The Save button shows Saving / Saved / Failed."),
                    ("Save checklist", "One Start · one primary End · unique End names · splits use a decision or a parallel exit (parallel exits two or more)."),
                    ("Editing needs", "A draft (#Draft / #Rejected) plus <b>your checkout</b>. Otherwise read-only."),
                    ("Pending downgrade", "While your permission downgrade is pending, checkout and submission are refused."),
                ]},
                {"title": "Shortcuts at a glance", "pts": [
                    ("Editing", "<code>Ctrl+C/V</code> copy · <code>Ctrl</code>+drag duplicate · <code>Ctrl+Z</code>/<code>Ctrl+Shift+Z</code> · <code>Delete</code> · <code>F2</code> rename · <code>Shift+Enter</code> line break"),
                    ("Canvas", "<code>Space</code> pan · <code>Ctrl</code>+wheel zoom · <code>/</code> search · <code>S</code> subprocess list · <code>Esc</code> cancel / close"),
                    ("Tidying", "<code>Shift+L/K</code> auto layout · <code>Ctrl+G</code> group · <code>Alt+W/C/T/X</code> align · <code>Alt+R/V</code> distribute · <code>Shift</code>+drag axis lock"),
                    ("Navigation", "<code>Tab</code>/<code>Shift+Tab</code> along the flow · <code>]</code>/<code>[</code> highlight · <code>Alt+←/→</code> collapse panels · <code>Ctrl+Shift+E</code> PNG · <code>Ctrl+Enter</code> send"),
                    ("More", "<b>More shortcuts</b> at the bottom of the Outline keys card."),
                ]},
            ],
        },
        {
            "title": "Node Data", "short": "Node Data",
            "desc": "Attributes, per-run metrics, GMP classification, I/O &amp; conditions, and links.",
            "slides": [
                {"title": "Node attributes", "shot": True, "pts": [
                    ("Title · description", "Double-click or F2 renames. Body double-click or <b>Edit info</b> opens the edit dialog."),
                    ("BPM attributes", "Assignee (org directory) · Role · department (auto) · System · color."),
                    ("Role", "A role name separate from the assignee. Catalog autocomplete, aliases become canonical."),
                    ("System", "Matched to the system list. Unknown values become <b>Other</b> + source note."),
                    ("GMP · link", "Direct / Indirect / Non-GMP pill locks the color. URLs show as a badge."),
                ]},
                {"title": "The node edit dialog (tiles)", "shot": True, "pts": [
                    ("Tiles", "Type &amp; color · <b>Attributes</b> · <b>seven metrics</b> · <b>I/O &amp; conditions</b>."),
                    ("In-place popover", "Click a tile and type where you clicked. Enter applies, Esc cancels."),
                    ("Instant sync", "Values reach the node and inspector immediately. The footer is just <b>Done</b>; undo is <code>Ctrl+Z</code>."),
                    ("Cost tile", "₩ / $ tabs pick one currency. The other clears on save."),
                    ("Previous / next nodes", "Dock cards on both sides slide into editing the neighbor."),
                ]},
                {"title": "Roles &amp; the system catalog", "shot": True, "pts": [
                    ("Role row", "Under Assignee in the inspector. Admin role list autocomplete; free text is kept."),
                    ("Assignee 2 : Role 1", "One tile row in the edit and SP designation dialogs. Filled tiles show only the chip."),
                    ("Other + source note", "Systems outside the list. With a different note present: replace / append / cancel."),
                    ("On canvas", "Role at rest, <b>assignee chip</b> about 1 s after hover or select."),
                    ("Warning color", "Departments or people missing from the org chart. Roles are not checked."),
                ]},
                {"title": "Per-run metrics (seven)", "shot": True, "pts": [
                    ("Per single run", "Duration · touch time · cost (₩/$) · headcount · annual volume · FTE."),
                    ("h.mm notation", "<code>1.30</code> = 1 h 30 m. Shown as typed while editing and in CSV/Excel, <code>1h30m</code> elsewhere."),
                    ("One currency", "₩ / $ toggle. Switching warns that the other value clears, with Undo."),
                    ("Section Save", "Metrics and I/O sections apply via their <b>section Save button</b>."),
                    ("Subprocess nodes", "Only annual volume and FTE are edited directly. The other five inherit."),
                ]},
                {"title": "Inputs, outputs &amp; conditions", "shot": True, "pts": [
                    ("Row layout", "Number / data-form pill / item name. Click the dotted slot to set the data form."),
                    ("Import from node…", "Pull an upstream output or downstream input and stay Linked. Disconnect detaches."),
                    ("Link cues", "Link icon with a direction tooltip. Hovering lights up the peer node on canvas."),
                    ("Required / optional", "Input flag. Required shows a red tint on hover."),
                    ("Start / end conditions", "Free text, shown below the selected node on canvas."),
                ]},
            ],
        },
        {
            "title": "Subprocesses", "short": "Subprocesses",
            "desc": "Reference another map as a single step. Preview it, expand it, manage registration.",
            "slides": [
                {"title": "Adding as a link", "shot": True, "pts": [
                    ("A reference, not a copy", "Changes to the source map flow through."),
                    ("Library", "<code>S</code>, chosung search. Designated maps by default."),
                    ("Filter popover", "<b>Unregistered maps</b> switch · <b>Department</b> rows · <b>Role</b> pills."),
                    ("Version tracking", "New links follow the latest published version; pinning is possible. Duplicates are blocked."),
                    ("Subprocess tab", "On selection: designation info · maps linking this one · designated parameters."),
                ]},
                {"title": "Subprocess connections · exits per end", "shot": "manual8/en-sp-exits.jpg", "pts": [
                    ("Incoming", "Any of the four sides. Handles show only while dragging in."),
                    ("Outgoing", "Starts from one exit point on the right."),
                    ("Pick the end", "With several ends, dropping asks <b>which end continues</b>."),
                    ("One per end", "Per-end parallel in the right-click <b>Parallel exit</b> submenu."),
                    ("End badge", "<code>2/3</code> after the title, red <code>+N</code> when over."),
                ]},
                {"title": "Preview peek · Node tab", "shot": True, "pts": [
                    ("Open the peek", "Click a library row (or hover 2.5 s). Map name · owner · version · framework path."),
                    ("Flow preview", "Wheel zoom (100–300%), drag to pan. <b>Add to map</b> · <b>Open this map</b> float above."),
                    ("Node tab", "A live mock of the node you'd add: attributes, metric chips, GMP, conditions, I/O."),
                    ("Drag it in", "Drag the mock straight onto the canvas. Locked maps can still be added."),
                    ("Department chip", "Hover for the org info card."),
                ]},
                {"title": "Preview peek · Details tab", "shot": True, "pts": [
                    ("Designated attributes", "Department · assignee · system and the <b>subprocess metrics</b>."),
                    ("Everything listed", "Conditions · I/O · GMP. Empty values tone down to dashes."),
                    ("Meta", "Published version (v-number) · publish time · framework path."),
                ]},
                {"title": "Expand in place (inline)", "shot": True, "pts": [
                    ("Expand subprocess", "Right-click or the action bar. The published child embeds read-only in a tinted region."),
                    ("Region header", "Map name with an open icon. Framework maps add the 5-level path label."),
                    ("Right-click inside", "Open linked map (confirmation gate) · Collapse."),
                    ("Tab traversal", "Expanded children included. Child GMP pills are read-only."),
                    ("Double-click", "Opens the node edit dialog. There is no separate deep view."),
                ]},
                {"title": "Node polish &amp; opening the linked map", "pts": [
                    ("Node width", "Hover for the right-edge grip and drag (180 px–120%). Saved with the map."),
                    ("Framework pill", "Folder pill on registered links. Click or hover 3 s for the path peek."),
                    ("Open linked map", "Last item of the context menu. Disabled without access; confirmed before leaving."),
                    ("No access", "Shown without permission on the linked map. Double-click edits annual volume and FTE only."),
                ]},
                {"title": "Linking unregistered maps", "shot": True, "pts": [
                    ("Unregistered maps switch", "Top of the Filter popover. Shown with a <b>Not registered</b> badge."),
                    ("Registration request", "Drop, confirm the warning, then Send request / Link only."),
                    ("Owner's Inbox", "The request lands there. Once designated, the warning clears and you're notified."),
                    ("From the node", "<b>Request registration</b> button with a status badge and withdraw."),
                    ("Create map \"query\"", "Under the library search. Makes a new map and links it here."),
                ]},
                {"title": "Managing designation (owner)", "shot": True, "pts": [
                    ("Subprocess designation", "Map Settings. Needs a published version. Values render live on every linking node."),
                    ("Three sections", "<b>Attributes</b> (department required) · <b>Metric tiles</b> (Σ suggestions) · <b>Detail tiles</b> (I/O data forms)."),
                    ("Reference values", "Annual volume and FTE. Each linking node keeps its own."),
                    ("No separate description", "The <b>map description</b> is used in the library and on linking nodes."),
                    ("Linked from", "Accordion of linking maps. The inspector's Subprocess tab opens the dialog via <b>Edit</b>."),
                ]},
            ],
        },
        {
            "title": "Versions &amp; Approval", "short": "Versions",
            "desc": "The draft → review → publish workflow, checkout, comments, and the inbox.",
            "slides": [
                {"title": "Versions &amp; statuses", "shot": True, "pts": [
                    ("Many versions", "As-Is / To-Be / free labels. A new one starts as a full copy."),
                    ("One draft at a time", "A new version only after the current one publishes. Numbers are assigned at publish."),
                    ("Statuses", "#Draft · #Pending · #Approved · #Published · #Rejected · #Expired (terminal)."),
                    ("Expiry", "Publishing expires the previous version. Republish starts a fresh cycle."),
                    ("L5 canvases", "<b>Confirmed</b> instead of publishing. No approvals, approvers or collaborators (⑨)."),
                ]},
                {"title": "Checkout (single writer)", "pts": [
                    ("One person", "A draft is checked out to one person. Others see a \"{name} is editing\" banner."),
                    ("Request / transfer", "The holder (or owner / sysadmin) approves from the Inbox or hands it over."),
                    ("No auto-release", "Changes only by transfer, an approved request, or a sysadmin takeover."),
                    ("On rejection", "The checkout returns to the submitter. Nobody can grab it in between."),
                ]},
                {"title": "From draft to published", "pts": [
                    ("① Request approval", "Check the approvers, add a comment. <b>AI draft</b> writes a 2–4 line rationale."),
                    ("② Approve / reject", "Rejections need a reason. Approval is unanimous."),
                    ("③ Publish", "<b>Only the submitter</b> publishes. The previous version expires."),
                    ("Withdraw", "Pending / Approved by the submitter only, Rejected also by owner / admin. The withdrawer gets the checkout."),
                    ("Self-publish", "If you're the only approver, one popover runs approve → publish."),
                    ("Bundle visibility", "Owners attach a visibility change that applies at publish."),
                ]},
                {"title": "Comments &amp; history", "pts": [
                    ("Stored with history", "Comments from submit / approve / publish / withdraw dialogs."),
                    ("Speech-bubble button", "On versions with comments. Opens the history modal."),
                    ("Approval tab", "Per-approver tag pills (hover = time and comment), progress n/m, waiting-on pills."),
                    ("Change summary", "Delta vs the published version (nodes and edges), collapsible."),
                    ("Rejection banner", "On top of a rejected version: who and why."),
                ]},
                {"title": "Approver landing &amp; Compare with published", "shot": True, "pts": [
                    ("Landing", "A pending version awaiting you opens first (<code>?version=</code> still wins)."),
                    ("On another version", "An <b>Awaiting your approval: {version}</b> link plus an overlay on the workflow section."),
                    ("Compare with published", "Approval tab button on the pending version. Latest published ↔ pending, with the AI summary."),
                    ("Why the overlay", "So you never decide on the wrong version. Approve or reject after opening it."),
                ]},
                {"title": "The approvals inbox", "shot": True, "pts": [
                    ("Review queue", "Version approvals · checkout transfers · permission / visibility · renames · SP registration · confirm requests · slot changes."),
                    ("Act inline", "Approve / reject with a reason, Open map. The Inbox tab shows a pending-count badge."),
                    ("SP registration card", "<b>Designate &amp; approve</b>. Saving the form approves."),
                    ("Confirm request card", "Direct L5 admin · sysadmin. Approving confirms the canvas; failing gates block it."),
                    ("Bundled requests", "Shown as read-only \"Decided with version approval\" rows."),
                ]},
            ],
        },
        {
            "title": "Comparing Versions", "short": "Compare",
            "desc": "Read differences in color, and summarize them in numbers.",
            "slides": [
                {"title": "Opening &amp; picking versions", "shot": True, "pts": [
                    ("Open", "<b>Compare</b> in the editor top bar (needs a published version) or the Map tab button."),
                    ("Base / Target", "Before / after captions. Echoed under the Changes panel."),
                    ("Dropdown rows", "Status pill and last-updated date. The other side's pick: <b>click to swap</b>."),
                    ("Layout", "Horizontal / vertical toggle. Drag overlapping nodes temporarily."),
                    ("First view", "Base = published, target = the newest other version. Resizable panel, eye icon for display fields."),
                ]},
                {"title": "Reading the diff", "shot": True, "pts": [
                    ("Color rules", "Added = green · Removed = red · Changed = yellow. Edge labels too."),
                    ("Per field", "New green, removed red struck-through. Parallel exit switches show as a field."),
                    ("Node chips", "Role, department, system and metric chips plus conditions. I/O collapses to <b>+N −M</b>."),
                    ("All / Changes only", "Properties pane toggle (default Changes only). Unchanged nodes are dimmed."),
                    ("Change list", "All / Nodes / Edges filter, click to focus. <b>Apply To-Be</b> · <b>Export</b> (PNG)."),
                ]},
                {"title": "The Summary tab", "shot": True, "pts": [
                    ("Version totals", "The seven metrics, base → target with deltas, plus contributing nodes."),
                    ("Sections", "Structure (node / edge counts) · Systems · Departments &amp; assignees · GMP."),
                    ("Summary items", "Top-right dropdown picks the visible sections."),
                ]},
                {"title": "The AI summary tab", "shot": True, "pts": [
                    ("Report for approvers", "Third tab. Opening it writes a bullet-style report (AI-enabled server)."),
                    ("Four blocks", "Revision summary · Flow &amp; control impact · Changes not in the submission comment · Questions before approval."),
                    ("Kept on the server", "Other approvers and reloads get the <b>saved report</b>. Draft edits regenerate it."),
                    ("Regenerate", "Title-row button discards the saved copy."),
                    ("Deep link", "<code>?base=&amp;target=</code>. Very large diffs send at most 200 nodes and 200 edges."),
                ]},
            ],
        },
        {
            "title": "Import · Export · AI", "short": "Data",
            "desc": "Fill from CSV, export as PNG · Excel · CSV, and draw with the AI assistant.",
            "slides": [
                {"title": "CSV import", "shot": True, "pts": [
                    ("Import CSV", "Top bar. Download the template, fill, upload. 25 columns, max 500 rows."),
                    ("Merge rule", "By name. Existing nodes keep color / comments / groups; blank cells keep values."),
                    ("Unknown column", "Columns outside the list are rejected."),
                    ("Normalization", "Assignees match by name. Role and system aliases become canonical; unknown systems become <b>Other</b>."),
                    ("Preview", "Added / Matched / Removed summary and warnings, then apply. A prompt for external AIs is provided."),
                ]},
                {"title": "Export (PNG · Excel · CSV)", "shot": True, "pts": [
                    ("PNG", "2× resolution with a map info card. <code>Ctrl+Shift+E</code>."),
                    ("Excel", "<b>Process Map</b> / <b>WBS</b>, then <b>pick columns</b>. No, Name, Type, Parallel and Next always stay. 2,000-row cap."),
                    ("CSV", "The same 25 columns as import, <b>picked columns</b> only. Round-trips; left-out columns keep their values. Name, Parallel and Next always stay."),
                    ("CSV skips", "Non-primary End nodes, edges into End, duplicate titles, with a warning. Secondary SP end links warn; per-end parallel is not carried."),
                ]},
                {"title": "AI assistant", "shot": True, "pts": [
                    ("Generate", "Flowcharts from plain language, attributes and metrics included. <b>Roles only</b>, never assignee names."),
                    ("Incremental edits", "Layout, colors and groups preserved. Nodes, links, inserts, labels, attributes, metrics, I/O, conditions, color, URL, parallel exits. Preview, then Apply."),
                    ("Analyze", "<b>Find issues</b> · summarize · walk-through · <b>Suggest improvements</b> · manual-grounded how-to."),
                    ("Chats stored", "Server-side, following you across devices. Several chats, other maps' chats readable."),
                    ("Input", "<code>Ctrl+Enter</code> sends · 2,000-char limit · adjustable text size."),
                ]},
                {"title": "AI consultant interview", "pts": [
                    ("Entry", "The <b>headset icon</b> in the top bar or the new-map balloon. Needs AI and an editable draft."),
                    ("Layout", "Working-map preview on the left, chat on the right. Click a node for <b>Ask about this</b>."),
                    ("How it asks", "Step by step with choice buttons. Never asks for assignee names. Unknowns: mark <b>TBD</b> and skip."),
                    ("Attach documents", "Attach SOPs and confirm <b>Draw now</b> to draft directly."),
                    ("Checkpoints", "Every step. Rolling back folds later steps into history."),
                    ("Finish", "Review and apply parameters, then <b>merge into draft</b> (by title). Check out the draft first."),
                ]},
            ],
        },
        {
            "title": "Framework &amp; Linkage Canvas", "short": "Framework",
            "desc": "Browse maps through the company framework (L1–L5) and draw cross-process linkage on L5 canvases.",
            "slides": [
                {"title": "The Framework view", "shot": True, "pts": [
                    ("Switch views", "Toggle above the home list: <b>Departments</b> / <b>Framework</b>. One level at a time."),
                    ("Siblings | children", "Two columns under the breadcrumb. A sibling swaps the right column, a child goes down."),
                    ("L5 cards", "State (Confirmed / Draft / No canvas) · admin · maps · <b>Open / Create canvas</b>."),
                    ("L5 only", "Maps attach to leaf categories. Non-L5 assignment or transfer is blocked."),
                    ("Search", "Results group by L5. Your position survives reloads and searches."),
                ]},
                {"title": "The hierarchy explorer", "shot": True, "pts": [
                    ("Open", "The <b>tree icon</b> by the breadcrumb. A floating panel that follows your drill-down."),
                    ("Tree tab", "Current path pre-expanded. Hovering a descendant highlights its ancestors."),
                    ("Diagram tab", "Ancestors → current → children → grandchildren, ERD-style. Right-click menu, <b>Whole tree</b> toggle."),
                    ("Search", "Substring and Korean initials. <b>Go</b> drills down."),
                ]},
                {"title": "The linkage canvas (L5)", "shot": True, "pts": [
                    ("Special canvas", "The category's L6 processes as subprocess nodes. No Start / End."),
                    ("Charcoal background", "Button by the <b>Level 5 map</b> tag switches to light. Draft / Confirmed / Superseded stamp."),
                    ("Who edits", "Category admins, higher grants inheriting downward. Single-writer checkout."),
                    ("No deletion", "Contained L6 nodes come from the classification. No approvals, publishing, approvers or SP designation."),
                    ("Notes", "Bottom of the Map tab. Entry / flow / open items for the category."),
                ]},
                {"title": "Who sees the draft", "pts": [
                    ("Live draft", "Before confirmation: admins of the category (or a parent) and sysadmins only."),
                    ("Everyone else", "Lands on the latest confirmed snapshot, or a \"not confirmed yet\" notice."),
                    ("Status banner", "<b>Draft</b> (amber) · <b>Confirmed</b> (read-only) · <b>Superseded</b> (older snapshot)."),
                    ("Server change guard", "After a slot change re-points the canvas, saving the old state is blocked with a reload notice."),
                    ("Version timeline", "Snapshots grouped by major, the newest labeled Latest confirmed."),
                ]},
                {"title": "Linkage canvas settings · Who can edit", "shot": True, "pts": [
                    ("Tabs", "Details · Who can edit · Visibility · Pending approvals · Checkout requests · Danger zone only."),
                    ("Who can edit", "Read-only. Category path, managing department, admins along the chain. Direct L5 admins carry <b>can confirm</b>."),
                    ("Change editors", "Adjust category admins or the managing department under Settings → Framework."),
                    ("Pending approvals", "This canvas's confirm and slot-change requests."),
                ]},
                {"title": "External L6 &amp; the L5 explorer", "shot": True, "pts": [
                    ("L5 explorer", "Top-left. See where you are and move to another L5's canvas."),
                    ("L6 picker", "Library button · right-click <b>Add L6 task</b> · <code>S</code>. Drag another category's L6 in."),
                    ("Origin badge", "Click for that L5's drill-in peek. \"Search other frameworks\" opens the browse modal."),
                ]},
                {"title": "Confirm &amp; versions", "shot": True, "pts": [
                    ("Six gates", "All L6 placed · no placeholders · no stale links · all L6 published · no exit-less loops · splits use a decision or a parallel exit."),
                    ("Who confirms", "The checkout holder if they are the <b>direct admin</b> (or a sysadmin). Higher admins send a confirm request."),
                    ("Versions", "v1.0 → v1.1 …, <b>Major</b> makes v2.0 and prunes intermediate minors."),
                    ("Changes required", "Layout-only moves can't confirm. The section shows changes since the last confirm."),
                    ("Snapshots", "Read-only from the version dropdown, comparable against each other."),
                ]},
                {"title": "Placeholders &amp; replacement", "shot": True, "pts": [
                    ("Dashed node", "An unregistered L6 slot. The bottom banner's <b>Connect</b> opens the dialog."),
                    ("Framework tree", "Auto-expanded to the guided L5. Click a map → preview → <b>Connect</b>."),
                    ("Outside the guided L5", "Asks for confirmation. Maps already on the canvas show as <b>placed</b>."),
                    ("Create placeholder", "Bottom of the L6 picker. The gate holds until it is connected."),
                ]},
                {"title": "Replacing stale links &amp; slot history", "shot": True, "pts": [
                    ("Three banners", "\"Removed from the framework\" · \"Handed over to (map)\" · \"Deleted\". Each offers <b>replace</b>."),
                    ("Stale links gate", "The node turns dashed and the confirm checklist catches it."),
                    ("Successor pinned", "Click the banner: the successor map is pinned as a recommendation card."),
                    ("Recently handed over", "Badge for 14 days on a node that just took over a slot."),
                    ("Slot history", "Hover an L6 node for assign · move · unassign · delete · hand-over with timestamps."),
                ]},
                {"title": "Drill-in peek &amp; browsing", "shot": True, "pts": [
                    ("Classification peek", "Origin badges on external L6s and folder pills on SP nodes."),
                    ("Search other frameworks", "A tree opened to the current path, with category and map search."),
                    ("Travel", "Clicking a map leaves the editor through a confirmation gate."),
                ]},
            ],
        },
        {
            "title": "Notifications · Notices · Collaboration", "short": "Staying in Sync",
            "desc": "Rich notifications, notices, feedback, and user groups.",
            "slides": [
                {"title": "Notifications", "shot": True, "pts": [
                    ("Rich sentences", "Map name, version and actor in your language. Actor pill = person card, version chip = version card."),
                    ("Bell", "Refreshes every 5 s. Clicking jumps to the tab and marks read."),
                    ("Notifications tab", "Mark all read, category filters, bulk delete by selection / read / date (permanent)."),
                    ("Data clean-up", "<b>Stale refs fix request</b> (one per owner) · <b>Owner assigned</b>."),
                    ("Retention", "The most recent 100 per person. Overflow auto-deletes oldest-first."),
                ]},
                {"title": "Notices &amp; the manual", "shot": True, "pts": [
                    ("Notices tab", "All / Important / General filters, search, Markdown bodies."),
                    ("Read mark", "Stored only in this browser (device)."),
                    ("Manual", "Top bar button. Document dropdown (KO/EN), searchable TOC and body."),
                ]},
                {"title": "Feedback &amp; user groups", "shot": True, "pts": [
                    ("Feedback", "Bug / Suggestion / Question / Other with your screen and open map attached. Track it on the Feedback page."),
                    ("Notes", "Anyone adds running memos. Edits keep history, deletion archives."),
                    ("User groups", "Request with 2+ members and 1+ manager, active after admin approval. Grant map access in one step."),
                    ("Managers", "Add / remove members · appoint managers · rename (once a week) · deactivate · delete (7-day trash)."),
                ]},
                {"title": "Quick FAQ", "pts": [
                    ("Can't edit?", "Check the banner: checkout, approval in progress, or Viewer role."),
                    ("Can't submit?", "Assign at least one approver first."),
                    ("Can't create a version?", "Finish the current draft cycle through publish."),
                    ("Copy disabled?", "Only maps published at least once can be copied."),
                    ("Won't save?", "One Start · one primary End · unique End names · splits use a decision or a parallel exit."),
                    ("Subprocess locked?", "It's undesignated. Request registration, or publish and designate."),
                    ("No draft on the canvas?", "Drafts are admin / sysadmin only. Everyone else lands on the latest confirmed snapshot."),
                    ("\"Owner unconfirmed\"?", "An interview-imported map. Map Settings → Danger Zone → Transfer ownership."),
                ]},
            ],
        },
    ],
}
